CC=/usr/intel/pkgs/gcc/4.6.2/bin/g++
CFLAGS= -lboost_iostreams -lboost_regex -lz -I/nfs/fm/disks/fm_cse_03758/tools/boost/1.43.0/include -L/nfs/fm/disks/fm_cse_03758/tools/boost/1.43.0/gcc4.3/lib64

all:
	$(CC) $(CFLAGS) StatParser.cpp ExprParser.cpp -o StatParser
